### ISSUE TITLE
I suggest cleaning the following sensitive contents from this repository.

### ISSUE THREAD

**Issue by ShikiSuen** [EggLinks/DanhengServer-Resources#1]
Contents meeting the following criteria are considered either leaked contents or internal test contents. Exposing such conntents on GitHub may result in DMCA removal of this repository.

1. All Character IDs in this range: `[6000, 8000)` && `[8900,+)`.
2. All Skill IDs in this range: `[7000000, 8000000)`.
3. All Ranks IDs in this range: `[700000, 800000)`.
4. In all language files, remove those contents which nameTextMapHash matches the contents above.

P.S.: If you clean, please use BFG repo cleaner to also clean them from previous commits. The fastest way might be to just remove the previous commits when you reupload the sanitized data.

**Comment by WatchAndyTW** [comment]
These data we provided are directly dumped from the released game files, which is the current official server's version. HoYoverse will still send DMCA strike to the repo even if you have removed those content, they do not allow any of their data got used / spread / exposed in the public
